PHPetshop/Controllers/PetsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace PHPetshop.Controllers {
    public class PetsController : Controller {
        public IActionResult Index() {
            return View();
        }

        [Authorize("admin")]
        public IActionResult Cadastrar() {
            return View();
        }

    }
}

PHPetshop/Controllers/ProdutosController.cs
using Microsoft.AspNetCore.Mvc;

namespace PHPetshop.Controllers {
    public class ProdutosController : Controller{
        public IActionResult Index() {
            return View();
        }
    }
}

PHPetshop/Controllers/ServicosController.cs
using Microsoft.AspNetCore.Mvc;

namespace PHPetshop.Controllers {
    public class ServicosController : Controller {
        public IActionResult Index() {
            return View();
        }
    }
}

PHPetshop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - PHPetshop</title>
        <link rel="stylesheet" href="~/css/normalize.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/navbar.css" />
        <link rel="stylesheet" href="~/css/footer.css" />
        @Html.Raw(StyleLoader.RenderStyleSection((string)ViewData["style"]))
        <script src="~/components/card.js" defer></script>
    </head>
    <body>
        <!--
            <nav class="navbar">
                <div class="nav-buttons">
                    <a href="/" class="navbar-brand">PH PetShop</a>
                    <ul>
                        <li class="nav-item">       
                            <a asp-controller="Pets" asp-action="Index" class="nav-link">Pets</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Servicos" asp-action="Index" class="nav-link">Serviços</a>  
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Produtos" asp-action="Index" class="nav-link">Produtos</a>                        
                        </li>
                        <li class="nav-item">       
                            <a asp-controller="Home" asp-action="Fale_Conosco" class="nav-link">Fale Cosnosco</a>
                        </li>
                        
                        <li class="nav-item">       
                            <a asp-controller="Pets" asp-action="Cadastrar" class="nav-link">Cadastrar</a>
                        </li>
                        
                    </ul>
                    <div class="d-flex">
                        @*

                        @{
                        var userClaim = @User.Claims.Where(x => x.Type.Contains("name")).FirstOrDefault();
                        }
                    @if(userClaim == null) {
                        <a asp-controller="Account" asp-action="Login" class="button-login">Login</a>
                    }else{
                        <a class="nav-link dropdown-toggle" role="button" id="UserOptionsDropdown" data-bs-toggle="dropdown">@userClaim.Value</a>
                        <ul class="dropdown-menu" aria-labelledby="UserOptionsDropdown">
                            <li><a class="dropdown-item" href="#">Editar Perfil</a></li>
                            <li><a class="dropdown-item" href="#">Meu Carrinho</a></li>
                            <li><hr class="dropdown-divider"/></li>
                            <li><a asp-controller="Account" asp-action="Logout" class="dropdown-item">Sair</a></li>
                        </ul>
                    }
                        *@
                    </div>  
                </div>
            </nav>

        -->
        <header>
        </header>
        <div class="container">
            <main role="main" class="">
                @RenderBody()
            </main>
        </div>
        <footer>
            <div class="footer-content">
                PH PetShop&copy Criado por <a href="https://github.com/PedroFSValladares" target="_blank">Pedro Valladares</a>
            </div>
        </footer>
        <script src="~/js/FormValidation.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>